config/routes.rb
Rails.application.routes.draw do
  resources :owners
  resources :cats
  resources :cats
  resources :owners
  get 'owners/index'

  get 'owners/show'

  get 'owners/update'

  get 'owners/new'

  get 'cats/index'

  get 'cats/show'

  get 'cats/update'

  get 'cats/new'

  resources :cats
  resources :owners

  root 'owners#index'
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  belongs_to :owners

  def full_details(show_all = true)
    "#{self.name} - #{self.age}"
  end

  def i
    "#{self.owners.name} - #{self.owner.age}"
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :cats

  def update_all_cats_to_the_same_info_that_i_am_passing_in(name, age, fur_color, ft, update_food = false)
    self.cats.each do |cat|
      cat.name = name
      cat.age = age
      cat.fur_color = fur_color
      cat.eye_color = ec
      cat.food_type = ft
      cat.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :kill_me

  def kill_me
    #raise "this is killing me"
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = []
    Cats.each do |cat|
      cats << cat
    end
  end

  def show
    @cat = Cat.find(perams[:id])
  end

  def edit
    x = params[:id]
    @cat = Cat.where(id: x)
  end

  def update
    @cat = Cat.find(params[:id])
    if @kat.update(cat_params)
      flash[:success] = "cat with id: #{params[:id]} updated"
      redirect_to cats_path
    else
      flash[:error] = "cat with id: #{params[:id]} not updated"
      redirect_to cats_path
    end
  end

  def new_cat
    @cat = Cat.new
  end

  def destory
    cat_id = params[:id]
    @cat = Cat.find(params[:id])
    if @cat
      if @cat.destroy
        flash[:success] = "cat destroyed"
      end
    end
    @cat.id
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat && @cat.save
      success_message = "cat was successfully saved."
      flash[:success] = success_message
      redirect_to cats_path
    else
      error_message = "cat was not succesfully saved."
      flash[:error] = error_message
      render "new"
    end
  end

  private
    def cat_params
      params.require(:cats).permit(:name, :age, :fur_color, :eye_color, :food_types)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owner = Owner.all.sort_by{|owner| owner.first_name }
  end

  def show
    @owner = nil
    @owner = Owner.find(params[:id])
    return @onr if @onr
  end

  def update
    @owner = Owner.find_by(id: params[:id])
    if @owner.update(owner_params)
      # redirect_to owners_path, success: "Owner with name #{params[:owner][:first_name]} #{params[:owner][:last_name]} was updated successfully"
    else
      flash[:error] = "Owner with name #{params[:owner][:first_name]} #{params[:owner][:last_name]} was not created successfully"
      # render 'edit'
    end
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to owners_path, success: "Owner with name #{@owner.first_name} #{@owner.last_name]} was created successfully"
    else

      redirect_to owners_path, success: "Owner with name #{@owner.first_name} #{@owner.last_name]} was not created successfully"

      redirect_to owners_path, success: "Owner with name #{params[:owner][:first_name]} #{params[:owner][:last_name]} was not created successfully"
    end
  end
  
  def edit
@owner = Owner.find_by(name: params[:owner][:name])
  end

  def destroy
    p = params[:id]
    message = nil
    success_message = ""
    error_message = ''
    @owner = Owner.find(params[:id])
    if @owner && @owner.persisted? && p
      #destroy all my cats
      @owner.cats.each do |cat|
        cat.destroy
      end
      if @owner.destroy
        success_message = "owner destroyed" 
        flash[:success] = success_message
        redirect_to owners_path
      end
    else
      error_message = "owner not destroyed because something happened with #{params[:id]}"
      flash[:error] = error_message
      redirect_to owners_path
    end 
  end

  # this method takes in an owner and sets its first cats age to 23
  def some_method_that_does_something(owner)
    cats = owner.cats
    cat = owner.cats.first
    cat.age = 22
    cat.save
  end

  def create_a_cat(owner, cat_name, a, cat_fur_color, ec, food_type)
    cat = Cat.new(name: cat_name, age: a, fur_color: cat_fur_color, eye_color: ec, food_type: food_type)
    if cat && cat.valid?
      owner.cats << cat
    else
      puts "cat not valid"
    end
  end

  private
    def op
      if params[:owner]
        params.require(:owner).permit(:first_name, :last_name, :age, :race, :location)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cats</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeSmells</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owner.each do |owner| %>
      <tr>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>